export const GETLIST = 'GETLIST';
export const SAVEFOLDER = 'SAVEFOLDER';
export const GETBYID = 'GETBYID';
export const SETFOLDERID = 'SETFOLDERID';
export const SETMOVING = 'SETMOVING';
export const UNSETMOVING = 'UNSETMOVING';
export const SETMOVINGIDFOLDER = 'SETMOVINGIDFOLDER';


